# Generated by Django 4.2 on 2024-06-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointaData11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor', models.CharField(choices=[('Heart', 'Heart Specialist'), ('Kidney', 'Kidney Specialist'), ('Cancer', 'Cancer Specialist'), ('Covid', 'Covid Specialist'), ('Surgeon', 'Surgeon'), ('Physician', 'Physician')], max_length=20)),
                ('time_slot', models.CharField(choices=[('9AM', '9 AM'), ('10AM', '10 AM'), ('11AM', '11 AM'), ('12PM', '12 PM'), ('1PM', '1 PM'), ('2PM', '2 PM'), ('3PM', '3 PM'), ('4PM', '4 PM'), ('5PM', '5 PM'), ('6PM', '6 PM')], max_length=4)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'appointdata1',
            },
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'loginuserdata',
            },
        ),
    ]
