# Generated by Django 5.0.4 on 2024-05-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
